"""baseline

M9 Task 2：把全部 13 张业务表编码进迁移基线。

⚠️ 本文件是 autogenerate 的产物，但已经**手工逐表核对**（不信任 autogenerate）：

- 13 张表全部在列，建表顺序满足外键依赖，downgrade 逆序删除；
- 每张表的 CHECK 约束与 `app/models.py::_TABLE_CHECKS` **逐条对齐**；
- 复合外键（`(run_id, task_id)` 等四处）完整保留 —— 它们是
  "跨任务拼接"防线的数据库侧保证；
- `uq_parse_cache_key` 部分唯一索引带 `postgresql_where` —— **少了它，
  解析缓存闸门在 PG 下会退化成全局唯一**（失败后无法重新解析），
  这是设计文档点名的迁移地雷；
- `server_default` 统一为 `CURRENT_TIMESTAMP`（方言中性，SQLite/PG 皆可）。

结构正确性由 `tests/postgres/test_migrations.py` 的往返 + 结构比对测试
持续守住；与 SQLite `db/schema.sql` 的关系是"结构等价"而非"逐字相同"
（列默认值在 SQLite DDL 有、ORM 无的，以 ORM 为准显式编码）。

Revision ID: 20260914_0001
Revises: 
Create Date: 2026-09-16 10:20:54.394071
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20260914_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('approval_code', sa.String(), nullable=False),
    sa.Column('approval_title', sa.String(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('apply_time', sa.String(), nullable=True),
    sa.Column('form_data_json', sa.Text(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=False),
    sa.Column('write_status', sa.String(), nullable=False),
    sa.Column('our_party_name', sa.String(), nullable=True),
    sa.Column('our_party_contract_label', sa.String(), nullable=True),
    sa.Column('our_party_business_role', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('context_source', sa.String(), nullable=False),
    sa.Column('context_status', sa.String(), nullable=False),
    sa.Column('context_conflict_json', sa.Text(), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('blocked_stage', sa.String(), nullable=True),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("blocked_stage IS NULL OR blocked_stage IN ('pull', 'detail', 'download', 'parse', 'rule', 'result', 'writeback')"),
    sa.CheckConstraint("context_source IN ('approval_system', 'manual')"),
    sa.CheckConstraint("context_status IN ('complete', 'missing', 'conflict', 'confirmed')"),
    sa.CheckConstraint("contract_type IS NULL OR contract_type IN ('procurement', 'sales', 'software_service', 'development', 'outsourcing', 'lease', 'other', 'unknown')"),
    sa.CheckConstraint("our_party_business_role IS NULL OR our_party_business_role IN ('buyer', 'seller', 'customer', 'service_provider', 'licensor', 'licensee', 'other', 'unknown')"),
    sa.CheckConstraint("our_party_contract_label IS NULL OR our_party_contract_label IN ('party_a', 'party_b', 'other', 'unknown')"),
    sa.CheckConstraint("task_status IN ('pending', 'parsing', 'reviewing', 'blocked', 'done')"),
    sa.CheckConstraint("write_status IN ('not_written', 'writing', 'success', 'failed')"),
    sa.CheckConstraint('length(trim(approval_code)) > 0'),
    sa.CheckConstraint('length(trim(instance_id)) > 0'),
    sa.CheckConstraint('length(trim(provider)) > 0'),
    sa.CheckConstraint('length(trim(tenant_id)) > 0'),
    sa.CheckConstraint('retry_count >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'tenant_id', 'instance_id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('event_status', sa.String(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('last_error_text', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("event_status <> 'delivered' OR delivered_at IS NOT NULL"),
    sa.CheckConstraint("event_status = 'delivered' OR delivered_at IS NULL"),
    sa.CheckConstraint("event_status IN ('pending', 'delivered', 'failed')"),
    sa.CheckConstraint('attempt_no >= 0'),
    sa.CheckConstraint('length(trim(aggregate_type)) > 0'),
    sa.CheckConstraint('length(trim(event_type)) > 0'),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0'),
    sa.CheckConstraint('length(trim(payload_json)) > 0'),
    sa.CheckConstraint('max_attempts >= 1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_outbox_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('idx_outbox_claim', 'outbox_events', ['event_status', 'next_retry_at'], unique=False)
    op.create_index('idx_outbox_lease', 'outbox_events', ['lease_expires_at'], unique=False)
    op.create_table('review_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('rule_category', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('rule_status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('match_mode', sa.String(), nullable=False),
    sa.Column('applies_when_json', sa.Text(), nullable=True),
    sa.Column('match_text', sa.Text(), nullable=False),
    sa.Column('fallback_match_json', sa.Text(), nullable=True),
    sa.Column('exclude_text', sa.Text(), nullable=True),
    sa.Column('suggestion_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("match_mode IN ('keyword', 'regex', 'llm', 'expr')"),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')"),
    sa.CheckConstraint("rule_status IN ('active', 'inactive')"),
    sa.CheckConstraint('length(trim(rule_code)) > 0'),
    sa.CheckConstraint('priority >= 0'),
    sa.CheckConstraint('rule_version >= 1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('approval_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_checksum', sa.String(), nullable=True),
    sa.Column('object_key', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('download_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("download_status IN ('pending', 'success', 'failed')"),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0'),
    sa.CheckConstraint('length(trim(attachment_id)) > 0'),
    sa.CheckConstraint('length(trim(file_name)) > 0'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'attachment_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("action IN ('RESULT_CONFIRMED', 'CONTEXT_CONFIRMED', 'WRITEBACK_REQUESTED', 'WRITEBACK_DELIVERED', 'TASK_RETRIED', 'RULE_CREATED', 'RULE_UPDATED')"),
    sa.CheckConstraint('length(trim(actor_name)) > 0'),
    sa.CheckConstraint('length(trim(target_type)) > 0'),
    sa.CheckConstraint('target_id >= 1'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_events', ['action'], unique=False)
    op.create_index('idx_audit_task', 'audit_events', ['task_id', 'created_at'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.Column('log_content', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("log_level IN ('debug', 'info', 'warning', 'error')"),
    sa.CheckConstraint('length(trim(log_type)) > 0'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('input_digest', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_token', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('job_status', sa.String(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_json', sa.Text(), nullable=True),
    sa.Column('last_error_code', sa.String(), nullable=True),
    sa.Column('last_error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("job_status IN ('queued', 'running', 'retry_wait', 'succeeded', 'failed')"),
    sa.CheckConstraint("job_type IN ('pull', 'detail', 'download', 'parse', 'rule', 'result', 'writeback')"),
    sa.CheckConstraint('attempt_no >= 0'),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0'),
    sa.CheckConstraint('length(trim(input_digest)) > 0'),
    sa.CheckConstraint('length(trim(input_json)) > 0'),
    sa.CheckConstraint('max_attempts >= 1'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('contract_parses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('basic_info_json', sa.Text(), nullable=True),
    sa.Column('clause_info_json', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parse_error_code', sa.String(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('config_digest', sa.String(), nullable=True),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('source_checksum', sa.String(), nullable=True),
    sa.Column('parse_version', sa.Integer(), nullable=False),
    sa.Column('text_coverage', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("parse_status IN ('pending', 'parsing', 'succeeded', 'failed', 'blocked')"),
    sa.CheckConstraint('ocr_confidence IS NULL OR (ocr_confidence >= 0 AND ocr_confidence <= 1)'),
    sa.CheckConstraint('ocr_pages IS NULL OR ocr_pages >= 0'),
    sa.CheckConstraint('parse_version >= 1'),
    sa.CheckConstraint('text_coverage IS NULL OR (text_coverage >= 0 AND text_coverage <= 1)'),
    sa.ForeignKeyConstraint(['attachment_id'], ['approval_attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id', 'parse_version'),
    sa.UniqueConstraint('id', 'task_id')
    )
    op.create_index('uq_parse_cache_key', 'contract_parses', ['attachment_id', 'cache_key'], unique=True, sqlite_where=sa.text("parse_status IN ('pending', 'parsing', 'succeeded')"), postgresql_where=sa.text("parse_status IN ('pending', 'parsing', 'succeeded')"))
    op.create_table('parse_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("kind IN ('standard_document', 'ocr_pages')"),
    sa.CheckConstraint('artifact_version >= 1'),
    sa.CheckConstraint('size_bytes >= 0'),
    sa.ForeignKeyConstraint(['parse_id'], ['contract_parses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parse_id', 'kind', 'artifact_version')
    )
    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('parse_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('context_snapshot_json', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(), nullable=True),
    sa.Column('ruleset_snapshot_json', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('run_status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("run_status IN ('running', 'completed', 'failed')"),
    sa.CheckConstraint('version_no >= 1'),
    sa.ForeignKeyConstraint(['parse_id', 'task_id'], ['contract_parses.id', 'contract_parses.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'task_id'),
    sa.UniqueConstraint('task_id', 'version_no')
    )
    op.create_table('review_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('overall_risk_level', sa.String(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('focus_points_json', sa.Text(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('result_fingerprint', sa.String(), nullable=False),
    sa.Column('supersedes_result_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('manual_confirmed', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('content_digest', sa.String(), nullable=True),
    sa.Column('confirmed_digest', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("overall_risk_level IN ('low', 'medium', 'high')"),
    sa.CheckConstraint("review_status IN ('complete', 'needs_review')"),
    sa.CheckConstraint('confirmed_digest IS NULL OR content_digest IS NOT NULL'),
    sa.CheckConstraint('hit_count >= 0'),
    sa.CheckConstraint('length(trim(result_fingerprint)) > 0'),
    sa.CheckConstraint('manual_confirmed IN (0, 1)'),
    sa.CheckConstraint('needs_review_count >= 0'),
    sa.CheckConstraint('not_applicable_count >= 0'),
    sa.CheckConstraint('version_no >= 1'),
    sa.ForeignKeyConstraint(['run_id', 'task_id'], ['review_runs.id', 'review_runs.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_result_id', 'task_id'], ['review_results.id', 'review_results.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'task_id'),
    sa.UniqueConstraint('run_id', 'result_fingerprint'),
    sa.UniqueConstraint('task_id', 'version_no')
    )
    op.create_table('rule_hits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('hit_status', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_position', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('hit_detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("hit_status IN ('hit', 'not_hit', 'not_applicable', 'needs_review')"),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')"),
    sa.CheckConstraint('rule_version >= 1'),
    sa.ForeignKeyConstraint(['rule_id'], ['review_rules.id'], ),
    sa.ForeignKeyConstraint(['run_id', 'task_id'], ['review_runs.id', 'review_runs.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'rule_id')
    )
    op.create_table('comment_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('write_status', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('content_digest', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('write_response_text', sa.Text(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("write_status IN ('not_written', 'writing', 'success', 'failed')"),
    sa.CheckConstraint('attempt_no >= 1'),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0'),
    sa.ForeignKeyConstraint(['review_id', 'task_id'], ['review_results.id', 'review_results.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_logs')
    op.drop_table('rule_hits')
    op.drop_table('review_results')
    op.drop_table('review_runs')
    op.drop_table('parse_artifacts')
    op.drop_index('uq_parse_cache_key', table_name='contract_parses', sqlite_where=sa.text("parse_status IN ('pending', 'parsing', 'succeeded')"), postgresql_where=sa.text("parse_status IN ('pending', 'parsing', 'succeeded')"))
    op.drop_table('contract_parses')
    op.drop_table('workflow_jobs')
    op.drop_table('task_logs')
    op.drop_index('idx_audit_task', table_name='audit_events')
    op.drop_index('idx_audit_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('approval_attachments')
    op.drop_table('review_rules')
    op.drop_index('idx_outbox_lease', table_name='outbox_events')
    op.drop_index('idx_outbox_claim', table_name='outbox_events')
    op.drop_index('idx_outbox_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('approval_tasks')
    # ### end Alembic commands ###
